version: '3.8'

services:
  master-namenode:
    build:  
      context: ./config/
      dockerfile: Dockerfile-master
    container_name: master-namenode
    hostname: master-namenode
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8090:8090"
      - "8080:8080"
      - "18080:18080"
    networks:
      - hadoop
    volumes:
      - hadoop-namenode:/var/hdfs/name
      - ./app:/app
      - ./app2:/app2
      - ./sparkDataWarehouse:/sparkDataWarehouse
      # - ./dhw1:/dhw1
      # - ./dhw2:/dhw2

  worker-datanode1:
    build:
      context: ./config/
      dockerfile: Dockerfile-worker
    container_name: worker-datanode1
    hostname: worker-node1
    depends_on:
      - master-namenode
    ports:
      - "8081:8081"
      - "9864:9864"
    networks:
      - hadoop
    volumes:
      - hadoop-datanode1:/var/hdfs/data

  worker-datanode2:
    build: 
      context: ./config/
      dockerfile: Dockerfile-worker
    container_name: worker-datanode2
    hostname: worker-node2
    depends_on:
      - master-namenode
    ports:
      - "8082:8081"
      - "9865:9864"
    networks:
      - hadoop
    volumes:
      - hadoop-datanode2:/var/hdfs/data

  postgres:
    build:
      context: ./config/
      dockerfile: Dockerfile-postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - hadoop
    volumes:
      - postgres-data:/var/lib/postgresql/data

  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge

volumes:
  hadoop-namenode:
  hadoop-datanode1:
  hadoop-datanode2:
  postgres-data: